spring:
  application:
    name: workout-kubernetes-pod-springboot-gradle

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
#      probes:
#        enabled: true
      show-details: always
#      status:
#        http-mapping:
#          DOWN: 503
#          OUT_OF_SERVICE: 503
#          UNKNOWN: 200
#          UP: 200
#        order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP